# NumPy III

In [1]:
import numpy as np

## Operaciones matemáticas y estadísticas

- `sum` : Suma de elementos.
- `mean` : Media aritmética de los elementos.
- `median` : Mediana de los elementos.
- `std` : Desviación estándar de los elementos.
- `var` : Varianza de los elementos.
- `min` : Valor mínimo de los elementos.
- `max` : Valor máximo de los elementos.
- `argmin` : Índice del valor mínimo.
- `argmax` : Índice del valor máximo.
- `cumsum` : Suma acumulada de los elementos.
- `cumprod` : Producto acumulado de los elementos.

**Ojo**. Al contrario que las operaciones unitarias que se vieron en el apartado anterior y que debían ser denominadas:
```python
np.sqrt(array)
```

Ahora algunas se puede volver a denominar todo en su manera más intuitiva, como por ejemplo:
```python
array.mean()
```

Aunque otras como `median` no lo permiten
```python
np.median(array)
```

In [2]:
array = np.random.randn(1000)

In [3]:
array.mean()

0.011731683581133783

In [4]:
array.std()

0.9819661035319387

In [5]:
array.std()/np.sqrt(1000)

0.031052494722416397

In [6]:
array.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [33]:
np.median(array)

0.01591508286507074

In [34]:
array.max()

3.103894141352079

In [35]:
array.argmax()

255

In [36]:
array[array.argmax()]

3.103894141352079

- Si el **array es multidmensional**:
    - Estas funciones poseen un parámetro `axis` que indica el eje sobre el cual aplicar la operación deseada
    - Si no se especifica, se calcula sobre todo el array ignorando su estructura
- Por lo general (axis=0 o axis=1), pero si es tridimensional el array, se puede poner (axis=3).
    - Sin embargo, como se ha explicado apenas se usan arrays tridimensionales.

-  Con esto se crea un array de tres dimensiones

In [7]:
np.random.normal(1000)
array.resize(10,10,10)

In [8]:
array.mean()

0.011731683581133783

In [9]:
array.mean(axis=2)

array([[ 0.19141049,  0.16555401, -0.48929031,  0.34764533,  0.11007613,
         0.03229787,  0.0041905 , -0.11062929, -0.21677821,  0.2893059 ],
       [ 0.31583324, -0.58955396, -0.17185037, -0.09902011, -0.0623398 ,
         0.02098077,  0.15058378, -0.11547674,  0.11082046, -0.28532486],
       [-0.19075646, -0.28059256, -0.02510136,  0.0734391 ,  0.51323577,
        -0.11000221,  0.37274284, -0.01982125,  0.47860018, -0.51669987],
       [ 0.26436772, -0.21829634,  0.06651803,  0.15200973,  0.30486824,
         0.21352558, -0.16315732, -0.75509944, -0.1640047 ,  0.5252427 ],
       [ 0.25088864, -0.54428342, -0.36859352,  0.1450714 , -0.03076667,
        -0.51040052, -0.72417245,  0.02284983,  0.57413055, -0.13145019],
       [-0.16630588, -0.03637481,  0.0524476 , -0.32949975, -0.17658886,
         0.37644215, -0.10495585,  0.20233367,  0.26418098,  0.21110442],
       [ 0.0329107 ,  0.27105105, -0.54096766,  0.17530784, -0.05728588,
        -0.0410291 ,  0.30169911, -0.03958798

In [10]:
_.shape

(10, 10)

## Operaciones booleanas

- Se pueden hacer operaciones matemáticas sobre arrays booleanos
    - True -> 1
    - False -> 0

In [12]:
bool_array = np.array([False, True, True, False, True])

In [13]:
bool_array.sum()

3

In [14]:
bool_array.all()

False

In [15]:
bool_array.any()

True

In [16]:
~(bool_array)

array([ True, False, False,  True, False])

In [17]:
(~bool_array).any()

True

## Sorting
### `np.sort(array)` vs `array.sort()`
- `np.sort(array)` no es inplace
- `array.sort()` es inplace

In [19]:
array = np.random.randn(29)
array

array([-0.09588592,  0.29152699, -1.14898265, -0.76815833,  0.97149589,
        1.14441219, -0.53633286, -0.98098567, -2.25478251, -1.38405772,
        0.33589324, -0.42106756,  3.09498074,  0.07218609, -1.07168369,
        0.40030899,  0.05191281, -0.99783773, -0.98893875,  1.14457466,
        0.14299004, -0.03757572, -0.3149402 ,  0.86189098, -1.01588578,
       -0.74866874, -0.78251329, -0.1080248 ,  1.00547155])

In [20]:
np.sort(array)

array([-2.25478251, -1.38405772, -1.14898265, -1.07168369, -1.01588578,
       -0.99783773, -0.98893875, -0.98098567, -0.78251329, -0.76815833,
       -0.74866874, -0.53633286, -0.42106756, -0.3149402 , -0.1080248 ,
       -0.09588592, -0.03757572,  0.05191281,  0.07218609,  0.14299004,
        0.29152699,  0.33589324,  0.40030899,  0.86189098,  0.97149589,
        1.00547155,  1.14441219,  1.14457466,  3.09498074])

In [21]:
array

array([-0.09588592,  0.29152699, -1.14898265, -0.76815833,  0.97149589,
        1.14441219, -0.53633286, -0.98098567, -2.25478251, -1.38405772,
        0.33589324, -0.42106756,  3.09498074,  0.07218609, -1.07168369,
        0.40030899,  0.05191281, -0.99783773, -0.98893875,  1.14457466,
        0.14299004, -0.03757572, -0.3149402 ,  0.86189098, -1.01588578,
       -0.74866874, -0.78251329, -0.1080248 ,  1.00547155])

In [24]:
array.sort()
array

array([-2.25478251, -1.38405772, -1.14898265, -1.07168369, -1.01588578,
       -0.99783773, -0.98893875, -0.98098567, -0.78251329, -0.76815833,
       -0.74866874, -0.53633286, -0.42106756, -0.3149402 , -0.1080248 ,
       -0.09588592, -0.03757572,  0.05191281,  0.07218609,  0.14299004,
        0.29152699,  0.33589324,  0.40030899,  0.86189098,  0.97149589,
        1.00547155,  1.14441219,  1.14457466,  3.09498074])

## Operaciones de conjuntos

- `unique` : Elementos únicos
- `intersect1d` : Intersección de dos arrays
- `union1d` : Unión de dos arrays
- `in1d` : Array booleano que indica si cada elemento del primer array está contenido en el segundo.
- `setdiff1d` : Diferencia entre ambos conjuntos.
- `setxor1d` : Diferencia simétrica entre ambos conjuntos.

In [25]:
a = np.array(['python', 'R', 'C#', 'C++', 'R'])
b = np.array(['java', 'javascript', 'python', 'R'])

In [26]:
a.unique()

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [27]:
np.unique(a)

array(['C#', 'C++', 'R', 'python'], dtype='<U6')

In [29]:
np.union1d(a, b)

array(['C#', 'C++', 'R', 'java', 'javascript', 'python'], dtype='<U10')

In [30]:
np.intersect1d(a, b)

array(['R', 'python'], dtype='<U10')

In [31]:
np.in1d(a, b)

array([ True,  True, False, False])

## Operaciones de cálculo matricial

A través del módulo `linalg` podemos acceder a multitud de funciones de álgebra lineal (cálculo matricial)

- `diag` : Recupera la diagonal principal de una matriz.
- `dot` : Realiza el producto matricial de dos matrices.
- `trace` : Calcula la traza de una matriz.
- `det` : Calcula el determinante de una matriz.
- `eig` : Calcula los autovalores y autovectores de una matriz.
- `inv` : Calcula la inversa de una matriz.
- `qr` : Calcula la descomposición QR de una matriz.
- `svd` : Calcula la descomposición de valores singulares (Singular Value Decomposition) de una matriz.
- `solve` : Calcula el resultado del sistema lineal Ax = B donde A y B son las matrices de entrada y x la salida.
- `lstsq` : Calcula la solución de mínimos cuadrados a y = Xb, donde y y b son los parámetros de entrada y X la salida.

In [30]:
X = np.random.normal(loc=5, size=6).reshape(2,3)
Y = np.random.normal(loc=5, size=6).reshape(3,2)

In [31]:
X = np.random.randint(20, size=12).reshape(3,4)
Y = np.random.randint(20, size=12).reshape(4,3)

In [32]:
X

array([[13, 13, 15, 11],
       [14,  9,  1, 17],
       [ 8, 12, 15, 16]])

In [33]:
Y

array([[ 8, 10, 11],
       [ 1, 13,  3],
       [ 1,  0,  8],
       [16, 14,  4]])

In [34]:
X * Y

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [35]:
X.shape

(3, 4)

In [36]:
Y.shape

(4, 3)

In [37]:
X.dot(Y)

array([[308, 453, 346],
       [394, 495, 257],
       [347, 460, 308]])

In [38]:
np.dot(Y, X)

array([[332, 326, 295, 434],
       [219, 166,  73, 280],
       [ 77, 109, 135, 139],
       [436, 382, 314, 478]])

Se puede abriar con la arroba `@`

In [39]:
X @ Y

array([[308, 453, 346],
       [394, 495, 257],
       [347, 460, 308]])

In [40]:
Y @ X

array([[332, 326, 295, 434],
       [219, 166,  73, 280],
       [ 77, 109, 135, 139],
       [436, 382, 314, 478]])

In [41]:
M = np.random.normal(size=9).reshape(3, 3)
S = M.T @ M
S

array([[1.23133921, 0.29417309, 0.80665676],
       [0.29417309, 2.27284522, 1.63594894],
       [0.80665676, 1.63594894, 1.860338  ]])

In [42]:
from np.linalg import inv

ModuleNotFoundError: No module named 'np'

In [43]:
from numpy.linalg import inv, det, eig

In [44]:
S

array([[1.23133921, 0.29417309, 0.80665676],
       [0.29417309, 2.27284522, 1.63594894],
       [0.80665676, 1.63594894, 1.860338  ]])

In [45]:
det(S)

1.0474457058694

In [46]:
eig(S)

(array([3.93005842, 1.21512766, 0.21933635]),
 array([[-0.27350994, -0.8587877 , -0.43321589],
        [-0.69989122,  0.48663826, -0.52281496],
        [-0.65980648, -0.16020891,  0.73415837]]))

In [47]:
eig(S)[0].sum()

5.364522430405114

In [48]:
S.trace()

5.364522430405112

In [49]:
eig(S)[0].prod()

1.0474457058693998

In [50]:
det(S)

1.0474457058694

In [51]:
inv(S)

array([[ 1.48163421,  0.73740136, -1.29090586],
       [ 0.73740136,  1.56572507, -1.6966143 ],
       [-1.29090586, -1.6966143 ,  2.58925653]])

In [52]:
np.dot(S, inv(S))

array([[ 1.00000000e+00, -4.09549798e-17,  1.43158719e-16],
       [-6.45504826e-16,  1.00000000e+00,  5.90380304e-16],
       [-3.89797082e-16, -5.85320983e-16,  1.00000000e+00]])

In [53]:
_.round()

array([[ 1., -0.,  0.],
       [-0.,  1.,  0.],
       [-0., -0.,  1.]])

## Funciones financieras

|Función|Descripcción|
|----|---|
|`fv(rate, nper, pmt, pv[, when])`|Calcula el valor futuro.|
|`pv(rate, nper, pmt[, fv, when])`|Calcula el valor presente.|
|`npv(rate, values)`|NPV (Net Present Value) de una serie de flujo de cajas.|
|`pmt(rate, nper, pv[, fv, when])`|Calcula el pago total, principal y intéres.|
|`ppmt(rate, per, nper, pv[, fv, when])`|Calcula el pago contra el principal.|
|`ipmt(rate, per, nper, pv[, fv, when])`|Calcula la proporción del interés del pago.|
|`irr(values)`|Internal Rate of Return (IRR).|
|`mirr(values, finance_rate, reinvest_rate)`| Internal Rate of Return (IRR) Modificada.|
|`nper(rate, pmt, pv[, fv, when])`|Calcula el número de pagos periodicos|
|`rate(nper, pmt, pv, fv[, when, guess, tol, …])`|Calcula la tasa de interes por periodo.|


## Exportar arrays con NumPy

- Podemos usar funciones propias de NumPy para leer y escribir ficheros
    - `np.save()` -> En binario
    - `np.savez()` -> Varios arrays en binario
    - `np.savez_compressed()` -> Varios arrays comprimidos
    - `np.savetxt()` -> Texto plano
    - `np.load()` -> Cargar fichero    

In [54]:
array = np.random.randn(1000)

In [56]:
np.save('data.npy', array)

In [57]:
array_load = np.load('data.npy')

In [58]:
(array == array_load).all()

True

- Si queremos guardar varios arrays en el mismo fichero

In [63]:
a = np.random.randint(100, size=10)
b = np.random.randn(10)

In [64]:
np.savez('data.npz', a1=a, a2=b)

In [65]:
ab = np.load('data.npz')

In [67]:
list(ab.keys())

['a1', 'a2']

In [71]:
ab["a1"]

array([54, 55, 98, 65, 64, 53, 49, 44, 92,  2])

In [72]:
ab["a2"]

array([-0.87873257,  1.11657387,  0.69093284, -2.52963358,  1.48766482,
       -2.27960579,  0.62225435, -1.37675454,  1.07365899,  0.20108733])

- Compresión de archivos

In [73]:
np.savez_compressed('data_com.npz', a1=a, a2=b)

- Texto plano

In [71]:
np.savetxt('data.txt', array)

In [72]:
np.savetxt('ata.txt', array, fmt='%.2f')